### ISSUE TITLE
Allow relay to be started with read-only config via --config

### ISSUE THREAD

**Issue by laibe** [ithacaxyz/relay#237]
For deployment in k8s via helm charts it would be nice to start up relay without  `--endpoint` and `--fee-token` as required cli args. In the helm `values.yaml` we define the complete config that is then passed on read-only via `--config` and `--registry`, e.g.: `relay --config /config/config.toml --registry /config/registry.toml`

```yaml
# config.toml
config:
  server:
    address: 0.0.0.0
    port: 9119
  chain:
    endpoints:
      - https://odyssey.ithaca.xyz
    fee_tokens:
      - "0x238c8CD93ee9F8c7Edf395548eF60c0d2e46665E"
      - "0x706aa5c8e5cc2c67da21ee220718f6f6b154e75c"
  quote:
    ttl: 30
  quoteGas:
    user_op_buffer: 25000
    tx_buffer: 1000000
```

At the moment this is not supported since relay has `--endpoint` and `--fee-token` as required argument that overwrite what is defined in the `config.toml`. Additionally if `config.toml` is read-only everything defined there seems to be ignored.

```bash
error: the following required arguments were not provided:
  --endpoint <RPC_ENDPOINT>
  --fee-token <ADDRESS>

Usage: relay --endpoint <RPC_ENDPOINT> --quote-secret-key <SECRET_KEY> --fee-token <ADDRESS> --secret-key <SECRET_KEY> --config <CONFIG> --registry <REGISTRY>

For more information, try '--help'.
```

Workaround for now is to use cli args instead of providing `config.toml`, that works but is less flexible since the chart needs to be adjusted every time new cli args are added vs just updating the `values.yaml` and thereby the generated `config.toml`:

With cli args:

```bash
              cd /var/tmp;
              relay 
              --registry /config/registry.toml
              --endpoint {{ join " --endpoint " .Values.config.chain.endpoints }} 
              --fee-token {{ join " --fee-token " .Values.config.chain.fee_tokens }}
              --http.addr {{ .Values.config.server.address }}
              --http.port {{ .Values.config.server.port | int }}
              --quote-ttl {{ .Values.config.quote.ttl | int }}
              --user-op-gas-buffer {{ .Values.config.quoteGas.user_op_buffer | int }}
              --tx-gas-buffer {{ .Values.config.quoteGas.tx_buffer | int }}
```

vs with config:

```bash
relay --config /config/config.toml --registry /config/registry.toml
```
