### ISSUE TITLE
Improve registry.yaml format

### ISSUE THREAD

**Issue by onbjerg** [ithacaxyz/relay#637]
Currently the registry.yaml format is something like this:

```yaml
"1":
  - ETH
  - - 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
    - USDC
  - - 0xdac17f958d2ee523a2206206994597c13d831ec7
    - USDT
```

Notice the double dashes and loss of human readability. Instead, a more ideal form would be something like:

```yaml
"1":
  - kind: ETH
  - address: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
    kind: USDC
  - address: 0xdac17f958d2ee523a2206206994597c13d831ec7
    kind: USDT
```
