### ISSUE TITLE
Implement multichain e2e tests for base_sepolia and other networks

### ISSUE THREAD

**Issue by joshieDo** [ithacaxyz/relay#808]
Currently, multichain e2e tests are excluded from the `base_sepolia` CI variant to improve test reliability. However, we should implement proper multichain tests that can target base_sepolia and other networks.

## Background

The multichain e2e tests were excluded in commit 4963364 because they were causing issues with the base_sepolia CI variant. The current implementation in the test suite includes:

### Existing Multichain Tests
- `test_multichain_usdt_transfer` - Cross-chain USDT transfer test
- `test_multi_chain_setup` - Multi-chain environment setup
- `test_multi_chain_funding` - Multi-chain funding verification
- `test_multi_chain_token_balances` - Token balance verification across chains
- `test_multi_chain_mining` - Chain-specific block mining
- `test_multi_chain_relay_service` - Relay service multi-chain support

### Current CI Configuration
```yaml
# .github/workflows/unit.yml:86-90
- name: Set test filter
  run:  < /dev/null | 
    if [ "${{ matrix.variant }}" = "base_sepolia" ]; then
      echo "TEST_FILTER=(kind(lib) | kind(bin) | kind(proc-macro) | kind(test)) and not test(~multi*chain)" >> $GITHUB_ENV
```

## Related Code

- Test implementations: `tests/e2e/cases/multichain_usdt_transfer.rs`, `tests/e2e/cases/multi_chain.rs`
- CI configuration: `.github/workflows/unit.yml:86-90`
- Environment setup: `tests/e2e/environment.rs`

This would allow us to re-enable multichain tests for the base_sepolia variant while ensuring they work reliably across different network configurations.
